### ISSUE TITLE
 java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:8039 flg=0x1 }} to activity {com.example.test_img_transparent/com.example.test_img_transparent.TransparentImgcropActivity}: java.lang.NullPointerException

### ISSUE THREAD

**Issue by ithakurmohit** [ketanpatel25/Image-Cropping-In-Transparent-Area#2]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:8039 flg=0x1 }} to activity {com.example.test_img_transparent/com.example.test_img_transparent.TransparentImgcropActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5013)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5054)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.NullPointerException
        at java.io.File.<init>(File.java:283)
        at com.example.test_img_transparent.TransparentImgcropActivity.setPhoto(TransparentImgcropActivity.java:157)
        at com.example.test_img_transparent.TransparentImgcropActivity.onActivityResult(TransparentImgcropActivity.java:129)
        at android.app.Activity.dispatchActivityResult(Activity.java:8304)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5006)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5054) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7664) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by ithakurmohit** [comment]
How to solve
